newscoop/application/modules/admin/controllers/UserController.php, newscoop/application/modules/admin/forms/Geolocation.php, newscoop/application/modules/admin/forms/User.php, newscoop/application/modules/admin/views/scripts/user/edit.phtml, newscoop/application/modules/admin/views/scripts/user/geolocation.phtml, newscoop/src/Newscoop/NewscoopBundle/Resources/translations/geolocation.en.yml, newscoop/src/Newscoop/NewscoopBundle/Resources/translations/users.en.yml
=> CS-5597 - User attributes management through backend

newscoop/application/AppKernel.php, newscoop/application/configs/symfony/config.yml, newscoop/application/configs/symfony/routing.yml, newscoop/composer.json, newscoop/composer.lock, newscoop/src/Newscoop/NewscoopBundle/Resources/views/admin_layout.html.twig
Integrated: https://github.com/willdurand/BazingaJsTranslationBundle
=> AENV-308 - prepare environment for using translation messages in AES

newscoop/classes/Image.php
It will add date when image was uploaded, source of the image (remote), it will be set to approved if user is admin else unapproved.
=> CS-5638 - Attach image by URL is not working after restore backup

newscoop/admin-files/libs/ContextList/ContextList.php, newscoop/application/modules/admin/views/scripts/playlist/popup.phtml, newscoop/library/Newscoop/Entity/Repository/PlaylistRepository.php
View after loading data from server: ![zrzut ekranu 2015-02-03 16 19 21](https://cloud.githubusercontent.com/assets/298610/6022903/7796fe64-abc0-11e4-997f-d3135595a8bd.png)
=> CS-5659: Show article status, article type in playlists

newscoop/src/Newscoop/NewscoopBundle/Controller/PluginsController.php, newscoop/src/Newscoop/NewscoopBundle/Resources/translations/plugins_manager.en.yml, newscoop/src/Newscoop/NewscoopBundle/Resources/views/Plugins/index.html.twig
=> CS-5661 - Disable installing plugins from UI

newscoop/install/Resources/sql/upgrade/4.3.x/2014.01.14/tables.sql
Proper fix for description field is in:
install/Resources/sql/upgrade/4.3.x/2014.08.11/tables.sql
=> Removes changing the description field

.travis.yml, features/3_api_topics.feature, features/6_api_link_unlink_topic.feature, newscoop/install/Resources/sql/campsite_core.sql, newscoop/install/Resources/sql/campsite_demo_tables.sql, newscoop/install/Resources/sql/upgrade/4.4.x/2015.02.12/tables.sql, newscoop/library/Newscoop/Entity/Repository/UserTopicRepository.php, newscoop/library/Newscoop/Entity/User.php, newscoop/library/Newscoop/Entity/UserTopic.php, newscoop/library/Newscoop/Services/EmailService.php, newscoop/library/Newscoop/Services/UserTopicService.php, newscoop/src/Newscoop/GimmeBundle/Controller/TopicsController.php, newscoop/src/Newscoop/GimmeBundle/Controller/UserTopicsController.php, newscoop/src/Newscoop/GimmeBundle/Resources/config/routing.yml, newscoop/src/Newscoop/GimmeBundle/Resources/config/serializer/newscoop/User.yml, newscoop/src/Newscoop/GimmeBundle/Resources/config/serializer/newscoop/UserTopic.yml, newscoop/src/Newscoop/NewscoopBundle/Entity/Repository/TopicRepository.php, newscoop/src/Newscoop/NewscoopBundle/Services/TopicService.php, spec/Newscoop/GimmeBundle/Controller/TopicsControllerSpec.php, spec/Newscoop/GimmeBundle/Controller/UserTopicsControllerSpec.php
=> CS-5650 - Topics API - implement additional endpoints/methods & CS-5664

newscoop/library/Newscoop/Services/SchedulerService.php
allow for removing multiple jobs with only jobName and command
=> IM-2572: problems in system settings for plugin cron job

newscoop/application/configs/parameters/parameters.yml, newscoop/application/configs/symfony/security.yml, newscoop/src/Newscoop/NewscoopBundle/Resources/config/services.yml, newscoop/src/Newscoop/NewscoopBundle/Security/User/SimpleUserProvider.php
added new UserProvider to allow users to be added via json file
as per request
=> SITE-692: SSO integration support for Newscoop 4.3.x

features/bootstrap/RestContext.php, newscoop/admin-files/bugreporter/emailus.php, newscoop/admin-files/libs/ArticleList/ArticleList.php, newscoop/library/Newscoop/Entity/Repository/IssueRepository.php, newscoop/library/Newscoop/Entity/Repository/SectionRepository.php, newscoop/src/Newscoop/GimmeBundle/Controller/SectionsController.php, newscoop/src/Newscoop/NewscoopBundle/Controller/PlaylistsController.php, newscoop/src/Newscoop/NewscoopBundle/Services/TopicService.php
=> CS-5713 & fixes

features/4_api_link_unlink_topic_to_from_article.feature, newscoop/admin-files/bugreporter/emailus.php, newscoop/classes/ArticleIndex.php, newscoop/classes/BugReporter.php, newscoop/library/Newscoop/Installer/Services/UpgradeService.php, newscoop/library/Newscoop/Services/EmailService.php, newscoop/src/Newscoop/NewscoopBundle/Controller/TopicsController.php, newscoop/src/Newscoop/NewscoopBundle/Entity/Repository/TopicRepository.php, newscoop/src/Newscoop/NewscoopBundle/EventListener/LocaleListener.php, newscoop/src/Newscoop/NewscoopBundle/Resources/views/Comments/index.html.twig, newscoop/src/Newscoop/NewscoopBundle/Resources/views/Plugins/index.html.twig, newscoop/template_engine/classes/SubtopicsList.php, newscoop/template_engine/metaclasses/MetaTopic.php
=> 4.4 bugfixes

newscoop/library/Newscoop/Image/Rendition.php
Use correct width and height in cutoutu calculation, refresh image size after croping.
=> fix renditions cropping with in implementation

newscoop/src/Newscoop/NewscoopBundle/Services/SystemPreferencesService.php
=> optimized system preferences service

newscoop/src/Newscoop/GimmeBundle/Serializer/Article/RenditionsHandler.php
old implementations didn't included custom crop parameters
=> use real renditions url, add some details

newscoop/install/Resources/sql/upgrade/4.4.x/2015.03.19/init_order_in_playlists.php
=> CS-5773: Fixes issue with upgrade which doesn't take mixed returned

newscoop/library/Newscoop/Entity/Repository/CommentRepository.php, newscoop/src/Newscoop/GimmeBundle/Controller/CommentsController.php, newscoop/src/Newscoop/NewscoopBundle/Resources/public/css/comments.css, newscoop/src/Newscoop/NewscoopBundle/Resources/views/Comments/index.html.twig
+ show grey background on hidden comments rows in comments backend
manager
=> by default hide hidden comments for not admins on api

newscoop/application/configs/symfony/security.yml, newscoop/src/Newscoop/GimmeBundle/Controller/OauthController.php, newscoop/src/Newscoop/NewscoopBundle/Resources/config/services.yml, newscoop/src/Newscoop/NewscoopBundle/Security/Http/Authentication/AbstractAuthenticationHandler.php, newscoop/src/Newscoop/NewscoopBundle/Security/Http/Authentication/AbstractLogoutHandler.php, newscoop/src/Newscoop/NewscoopBundle/Security/Http/Authentication/AuthenticationFrontendSuccessHandler.php, newscoop/src/Newscoop/NewscoopBundle/Security/Http/Authentication/AuthenticationSuccessHandler.php, newscoop/src/Newscoop/NewscoopBundle/Security/Http/Authentication/FrontendLogoutSuccessHandler.php, newscoop/src/Newscoop/NewscoopBundle/Security/Http/Authentication/LogoutSuccessHandler.php, newscoop/src/Newscoop/NewscoopBundle/Security/Http/Authentication/OAuthLogoutSuccessHandler.php, newscoop/src/Newscoop/NewscoopBundle/Security/Http/Authentication/OAuthSuccessHandler.php
=> CS5777 - Create OAuth custom login & logout handlers

newscoop/library/Newscoop/Acl/Storage.php, newscoop/library/Resource/Acl.php
use array hydration for read only entities
Performance change on playlists save request (with 3 link actions)
Article edit screen loading
=> remove findBy and findAll methods

newscoop/library/Newscoop/Tools/Console/Command/GenerateWebcodeCommand.php, newscoop/library/Newscoop/WebcodeFacade.php
* use webcode facade instead new webcode generating
* persist webcodes with cascade option on entity
* do not check if webcode is unique in webcode generator - we are
checking it later with proper handling.
=> simplyfy and fix webcode (re)generate command

newscoop/template_engine/classes/SubtopicsList.php
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | CS-5754
| Doc PR        | https://wiki.sourcefabric.org/display/NsLingo/List+of+Subtopics
Added extra filter called: "direct". See the wiki page for more info.
=> CS-5754 - Problem with topics

newscoop/include/smarty/campsite_plugins/function.set_topic.php, newscoop/src/Newscoop/GimmeBundle/Controller/UsersController.php, newscoop/src/Newscoop/NewscoopBundle/EventListener/OldPluginsTranslationListener.php, newscoop/src/Newscoop/NewscoopBundle/Services/TopicService.php, newscoop/template_engine/classes/ArticlesList.php
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | CS-5754
| Doc PR        | -
I created one method to get topic by id, name or full name. Also fixed set_topic smarty function. Setting topic only by name (e.g. Software) didnt work. Its related to PR: https://github.com/sourcefabric/Newscoop/pull/1124
=> CS-5754 -set_topic issue fix & typo fix & removed unused method

newscoop/library/Newscoop/Entity/Author.php, newscoop/src/Newscoop/GimmeBundle/Controller/CommentsController.php, newscoop/template_engine/metaclasses/MetaSubtitle.php
+ fix uri parameters in metaSubtitle (editor_image.tpl)
=> add articles relation to Author table, fix comments api user checking

newscoop/bin/newscoop-backup
After a user had some issues i decided to add some more clear error messages.
=> CS-5791:  Adds more clear error messages when direcotires dont exist

newscoop/application/modules/admin/views/scripts/image/edit-image-data.phtml, newscoop/classes/Article.php, newscoop/classes/Log.php, newscoop/install/Resources/sql/upgrade/4.4.x/2015.05.16/tables.sql, newscoop/library/Newscoop/Entity/Article.php
* get webcode object from article
* remove webcode on article remove
* don’t put messages to log longer than 255 chars
* allways synchronize section_id and issue_id (on translations and
duplication)
=> translations fixes

newscoop/library/Newscoop/Tools/Console/Command/UpdateWeatherCommand.php
remove winter locations and add summer locations
=> MOTM-1339: Add Bathing weather (Badewetter) again to weather setup

newscoop/application/configs/services/services.yml, newscoop/library/Newscoop/Comment/SearchService.php
=> TW-203: Fixes error with comment search service

newscoop/install/Resources/sql/upgrade/4.4.x/2015.06.08/tables.sql
I've changed the old script and added a new one. Just to prevent a
temporary state of possible wrong data.
=> Adds correct way to update section_id in Articles table

newscoop/install/Resources/sql/upgrade/4.4.x/2015.03.19/init_order_in_playlists.php, newscoop/library/Newscoop/Services/PlaylistsService.php
improve removing left nodes, fix clearing Playlist templates, update order initializing script
=> Playlists fixes

newscoop/library/Newscoop/Entity/Repository/ArticleRepository.php, newscoop/library/Newscoop/Entity/Repository/PlaylistRepository.php, newscoop/src/Newscoop/GimmeBundle/Controller/ArticlesListController.php
#1154 must be merged first 
manual join needed article relations for api - it takes less time then left joining
=> Articles api join

newscoop/template_engine/metaclasses/MetaTopic.php
This fixes it, based on changes in 5c73ba0b4988589bcf1b94cf525309e7f193eeb5
=> When using tpid parameter page can get into an infinite loop

newscoop/admin-style/slideshow.css, newscoop/application/modules/admin/views/scripts/slideshow/edit-item.phtml, newscoop/application/modules/admin/views/scripts/slideshow/edit.phtml, newscoop/library/Newscoop/Criteria/SlideshowCriteria.php, newscoop/library/Newscoop/Package/PackageRepository.php, newscoop/library/Newscoop/Package/PackageService.php, newscoop/src/Newscoop/GimmeBundle/Controller/ArticlesController.php, newscoop/src/Newscoop/GimmeBundle/Controller/SlideshowsController.php, newscoop/src/Newscoop/GimmeBundle/Resources/config/serializer/newscoop/Item.yml, newscoop/src/Newscoop/GimmeBundle/Resources/config/serializer/newscoop/Package.yml, newscoop/src/Newscoop/GimmeBundle/Serializer/Image/ImageUriHandler.php, newscoop/src/Newscoop/NewscoopBundle/Resources/translations/articles.pl.yml, spec/Newscoop/GimmeBundle/Controller/SlideshowsControllerSpec.php
=> improved slideshows handling using API

newscoop/install/Resources/sql/campsite_core.sql, newscoop/install/Resources/sql/campsite_demo_data.sql, newscoop/install/Resources/sql/upgrade/4.4.x/2015.06.15/tables.sql
make IdPublication nullable with default 0
=> [CS-5808] [Fix] Creating additional publications does not work

newscoop/src/Newscoop/NewscoopBundle/Form/Type/PublicationType.php
=> [CS-5822] [Fix] publication management: switching url type does not work

newscoop/admin-files/article_types/index.php, newscoop/admin-files/libs/ArticleList/table.php, newscoop/src/Newscoop/NewscoopBundle/Resources/translations/article_types.en.yml, newscoop/src/Newscoop/NewscoopBundle/Resources/translations/library.en.yml
See https://dev.sourcefabric.org/browse/CS-5819 - these simple changes are meant to make the Article Type options easier to understand.
=> CS-5819 Clarify labels for Article Types

newscoop/template_engine/classes/CampTemplate.php
Initialize loader even when translations files are cached
=> [CS-5796] [Fix] Translation strings not loading

newscoop/application/layouts/scripts/admin.phtml
use value from head title in page titles again
=> [CS-5817] [Fix] Create New Account / Edit User Account headings missing

newscoop/src/Newscoop/NewscoopBundle/Menu/Builder.php
keep breadcrumbs for editing user
=> [CS-5074] [Fix] User management in backend: missing breadcrumbs for edit user view

newscoop/composer.json, newscoop/composer.lock
looks like that commit I used doesnt exist anymore
and it takes the latest dev-master
which works only with php >=5.4.0
also this will work with the php 5.3.10
=> remove jms serializer commit restriction from composer.json

newscoop/js/tinymce/plugins/campsiteinternallink/link.php
=> [CS-5815] [Fix] Internal link feature of TinyMCE plugin does not work on demo site

newscoop/install/Resources/sql/campsite_core.sql, newscoop/src/Newscoop/NewscoopBundle/Controller/CommentsController.php, newscoop/src/Newscoop/NewscoopBundle/Resources/views/Comments/index.html.twig
* [CS-5832] [Fix] deactivate comments ordering by article name, allow showing comments for pending articles.
* clean install sql and snipptets queries
=> Fixes 19 06

docker-compose.yml, docker/docker-entrypoint.sh
Change indentation for yml, shell to bash and tells tail to keep retrying,
=> Docker - minor fixes for linux (will still work on mac)

Dockerfile, docker-compose-dev.yml, docker/docker-entrypoint.sh, docker/docker-newscoop.yml, docker/newscoop-dev.conf
Running prod:
- docker-compose build
- docker-compose up
Running dev:
- docker-compose -f docker-compose-dev.yml build
- docker-compose -f docker-compose-dev.yml up
=> Adds prod/dev env switch and runs cron server

newscoop/js/admin.js, newscoop/src/Newscoop/NewscoopBundle/Controller/SecurityController.php, newscoop/src/Newscoop/NewscoopBundle/Resources/public/js/tree.js, newscoop/src/Newscoop/NewscoopBundle/Resources/views/Topics/index.html.twig
=> Topics fixes

newscoop/admin-files/articles/post.php, newscoop/template_engine/metaclasses/MetaArticle.php
* fix wrong cache key - make it unique per article not per whole publication
* clear cache key on comments status update from article save action
=> [TW-243] [Fix] Comment-function doesn't work

newscoop/admin-files/articles/edit.php, newscoop/classes/ArticleData.php
Fix cache key for storing user defined article type fileds in cache
=> [CS-5825] [Fix] Article Type field controls Show in Editor and Show/Hide have no function

newscoop/src/Newscoop/NewscoopBundle/Resources/public/js/playlists/controllers/featured-articles.js, newscoop/src/Newscoop/NewscoopBundle/Resources/public/js/playlists/controllers/playlists.js, newscoop/src/Newscoop/NewscoopBundle/Resources/translations/articles.en.yml
This PR fixes the issue with limit's modal. 
**Initially if there is no limit set for the list and:**
- you want to set the limit - a prompt will popup
- limit is the same and you click the save btn - no prompt will popup
**Initially there is a limit set for the list and:**
- you want to increase the limit - no prompt will popup
- you want to decrease the limit (but the new limit is not 0 or "empty value") - a prompt will popup
- you want to decrease the limit (a new limit is set to 0 or "empty value") - no prompt will popup
It will remove articles over the set limit instantly when changing the limit value accordingly.
=> CS-5802 - Featured Article List limits do not work as expected

newscoop/admin-files/article_types/fields/add.php, newscoop/admin-files/article_types/fields/index.php, newscoop/src/Newscoop/NewscoopBundle/Resources/translations/article_type_fields.en.yml
There is some ambiguity in the labels of Article Type fields which these changes are meant to make clearer.
=> CS-5825 Better labels and tooltips for Article Type field management

newscoop/library/Newscoop/Entity/Repository/ArticleRepository.php
Removed already defined joins.
=> BN-200 - Search article by author is not working in Playlist management

README.md, docker/docker-entrypoint.sh
Adds default cron and fixes cron commands. Now cronjobs also work.
=> Docker dev additions

newscoop/src/Newscoop/NewscoopBundle/Controller/PluginsController.php, newscoop/src/Newscoop/NewscoopBundle/Resources/translations/plugins_manager.en.yml, newscoop/src/Newscoop/NewscoopBundle/Resources/views/Plugins/index.html.twig
add check if private plugins directory is writable, if not provide some tips how to fix it.
=> [CS-5811] [Improvement] Interface for uploading private plugins results in white screen

newscoop/library/Newscoop/Entity/Repository/ArticleRepository.php, newscoop/library/Newscoop/Services/ArticleService.php, newscoop/src/Newscoop/GimmeBundle/Controller/ArticlesController.php
when no filers are selected - just get latest articles
=> [CS-5846] [Fix] Default order of available articles in featured article lists manager should be by recency

newscoop/classes/Article.php
fixed articles search by topics
=> fixed articles search by topics

newscoop/admin-files/libs/ContextList/ContextList.php
=> [CS-5853] [Fix] Date of articles in related articles search in the modal is always current day

newscoop/src/Newscoop/NewscoopBundle/Resources/translations/articles.en.yml, newscoop/src/Newscoop/NewscoopBundle/Resources/views/BackendArticleImages/edit.html.twig
add link to original image from article image edit view
=> [CS-5851] [Fix] Option to show photos in full size

newscoop/src/Newscoop/NewscoopBundle/Controller/CommentsController.php, newscoop/src/Newscoop/NewscoopBundle/Menu/Builder.php
=> [CS-5863] [Fix] User without user type can edit and delete comments

newscoop/application/modules/admin/views/scripts/application/help.phtml, newscoop/src/Newscoop/GimmeBundle/Resources/views/ConfigureApi/configure.html.twig, newscoop/src/Newscoop/NewscoopBundle/Resources/translations/api.en.yml, newscoop/src/Newscoop/NewscoopBundle/Resources/translations/help.en.yml
links are in:
* help page
* configure public resources
=> [Improvement] Add links to REST API documentation in admin ui

newscoop/admin-files/articles/edit_javascript.php, newscoop/src/Newscoop/NewscoopBundle/Resources/public/css/new-design.css, newscoop/src/Newscoop/NewscoopBundle/Resources/views/Topics/index.html.twig
=> CS-5868 & CS-5867

newscoop/library/Newscoop/Services/CommentService.php, newscoop/src/Newscoop/NewscoopBundle/Controller/CommentsController.php, newscoop/src/Newscoop/NewscoopBundle/Resources/views/Comments/index.html.twig
move search to header - it shows up more comments on first screen
=> use proper left join for comment thread

newscoop/src/Newscoop/NewscoopBundle/Controller/WebcodeRedirectController.php, newscoop/template_engine/classes/CampContext.php
* do not try to redirect for not published articles - just show 404.tpl
=> provide option to change preview mode, small fix for webcode redirect controller

newscoop/include/smarty/campsite_plugins/block.image.php, newscoop/template_engine/metaclasses/MetaImage.php
Pls review, but wait with merging.
=> TW-236: Disabled escaping when RichTextCaption setting is on

newscoop/admin-files/articles/edit_switches_box.php
that checkbox should be always in form, just hidden if not needed.
=> [CS-5896] [Fix] hide visible for non subscriber only when plugin is not enabled and article is public.

newscoop/src/Newscoop/NewscoopBundle/Resources/views/Comments/index.html.twig
=> removed reloading after removing comment, added option to check comment with just clicking in row

.travis.yml, features/7_api_link_unlink_playlist_article.feature, features/bootstrap/RestContext.php, newscoop/composer.json, newscoop/composer.lock, newscoop/library/Newscoop/Entity/Repository/PlaylistRepository.php, newscoop/library/Newscoop/Services/UserService.php, newscoop/library/Newscoop/Tools/Console/Command/CreateUserCommand.php, newscoop/src/Newscoop/GimmeBundle/Controller/ArticlesController.php
Added endpoint with the list of playlist the given article belongs to
=> Api article playlists

newscoop/install/Resources/sql/campsite_core.sql, newscoop/install/Resources/sql/upgrade/4.4.x/2015.08.24/tables.sql
=> Changes themes field to text (needed for multiple templates under

newscoop/install/Resources/sql/upgrade/4.4.x/2015.06.18/cronjobs.php, newscoop/install/Resources/sql/upgrade/4.4.x/2015.06.18/tables.sql, newscoop/library/Newscoop/Installer/Services/FinishService.php, newscoop/library/Newscoop/Services/SchedulerService.php
*Require changes in plugins as well.*
=> [wip] CS-5834: Implements relative paths for cron_jobs in database

newscoop/admin-files/users/authors.php, newscoop/classes/Author.php, newscoop/install/Resources/sql/upgrade/4.4.x/2015.09.15/data-required.sql, newscoop/src/Newscoop/NewscoopBundle/Resources/translations/users.en.yml
Implemented functionality to automatically trim author names and remove multiple spaces. This caused issues on multiple instances.
=> CS-5913: Implements optimized author ReadName mechanism

newscoop/library/Newscoop/Entity/Repository/ArticleRepository.php, newscoop/src/Newscoop/NewscoopBundle/Controller/PlaylistsController.php, newscoop/src/Newscoop/NewscoopBundle/Resources/public/js/playlists/controllers/playlists.js, newscoop/src/Newscoop/NewscoopBundle/Resources/views/Playlists/index.html.twig
Preloads featured article list by its identifier in database. An extra url parameter, with list id (`listId`), should be passed to `/admin/playlists/{articleNumber}/{language}/editor-view/{listId}`
=> preload featured article list by providing an extra parameter in url

newscoop/application/modules/admin/views/scripts/application/help.phtml
This seems like a good place for users to find a link to our translation project.
=> CS-5858 IN-1956 Add Transifex project link to Help page

newscoop/application/configs/symfony/security.yml, newscoop/application/controllers/AuthController.php, newscoop/application/controllers/DashboardController.php, newscoop/application/controllers/RegisterController.php, newscoop/application/plugins/Auth.php, newscoop/library/Newscoop/Entity/Repository/UserRepository.php, newscoop/src/Newscoop/CommunityTickerBundle/Services/CommunityFeedService.php, newscoop/src/Newscoop/NewscoopBundle/Controller/SecurityController.php, newscoop/src/Newscoop/NewscoopBundle/Controller/SystemPrefController.php, newscoop/src/Newscoop/NewscoopBundle/EventListener/LocaleListener.php, newscoop/src/Newscoop/NewscoopBundle/Resources/translations/system_pref.el.yml, newscoop/src/Newscoop/NewscoopBundle/Resources/views/SystemPref/index.html.twig, newscoop/src/Newscoop/NewscoopBundle/Security/Http/Authentication/AuthenticationFailedHandler.php, newscoop/src/Newscoop/NewscoopBundle/Security/Http/Authentication/AuthenticationSuccessHandler.php, newscoop/src/Newscoop/NewscoopBundle/Session/Storage.php
* remove connection between session lifetime and php gc
* allow to loginon frontend with username
* cover /auth with symfony firewall
=> [CS-5932] authentication changes

newscoop/classes/Author.php, newscoop/install/Resources/sql/campsite_core.sql, newscoop/src/Newscoop/GimmeBundle/Controller/OauthController.php, newscoop/src/Newscoop/NewscoopBundle/Controller/FeedController.php, newscoop/src/Newscoop/NewscoopBundle/Controller/UsersController.php, newscoop/template_engine/metaclasses/MetaAuthor.php, newscoop/themes/system_templates/_feed/default.tpl
=> [feature] implement feed controller

newscoop/application/controllers/AuthController.php, newscoop/application/controllers/RegisterController.php
remove case when user is already authenticated with Zend - id doesn't make sense - if you are authenticated - so you can login - if you can login when you already confirmed you account. 
added some code comments 
instead redirecting to (non existing) index controller - redirect of dashboard (when logged in user hits login page).
=> simplify registration confirmation

newscoop/application/controllers/AuthController.php, newscoop/application/controllers/RegisterController.php
Reverts sourcefabric/Newscoop#1327
=> Revert "simplify registration confirmation"

newscoop/library/Newscoop/Entity/Repository/UserRepository.php
=> fix filtering users by authors

newscoop/template_engine/classes/CampGetImage.php
Default limit is 3000px - can be configurable by setting (manually for now) settings in System Preferences.
=> Limit max cropped image height and width

newscoop/admin-files/articles/duplicate.php, newscoop/classes/Article.php, newscoop/src/Newscoop/NewscoopBundle/Resources/translations/api.en.yml
Fixes issue https://dev.sourcefabric.org/projects/CS/issues/CS-5973. 
List issues with information about it's language, allow to move articles between sections in translated issues
=> Article move fix 

newscoop/classes/Article.php, newscoop/classes/DatabaseObject.php
I originally assumed that the article shouldn't be copied if doing so would result in an exception thrown because of a violation constraint, so this pull request will contain 2 commits, the first of which is an implementation of that assumption, just in case this is actually what is required by the customer. At least we will have a record of this work.
=> Cs 5973v4.4
