sourcefabric/Newscoop

newscoop/application/controllers/RegisterController.php, newscoop/template_engine/metaclasses/MetaUser.php
***Benefits:***
- displaying user image's logic is simpler
- let's you read and resize images from the current theme directory
- images for each resolution are not required anymore (user_blank_120x120.jpg, user_blank_60x60.jpg etc)
This improvement lets you have more control over user avatars. It lets you read and crop images also from `themes` directory. You can now pass 3rd argument with default avatar path, for example:
```
{{ $user->image($height, $width, 'fit', '_img/user-thumb.jpg') }}
```
It means that file `user-thumb.jpg` from current theme (e.g `themes/publication_1/theme_1/_img/user-thumb.jpg`) will be taken and cropped by given `$height` and `$width`. 
If user has profile image, then to simply display it use (like it was before):
```
{{ $user->image($height, $width) }}
``` …
=> improve displaying blank avatars for users on frontend

newscoop/composer.json, newscoop/composer.lock
Updated smarty-dev 3.1.19 to smarty 3.1.21. Ran a composer install from the generated lock file and also a composer update and no errors.
=> CS-5645: Updates dependency smarty-dev 3.1.19 to smarty 3.1.21

features/3_api_topics.feature, features/4_api_link_unlink_topic_to_from_article.feature, features/bootstrap/RestContext.php, newscoop/library/Newscoop/Services/SchedulerService.php
***New feature for behat tests***
There is a possibility of saving value of the specific field from the response under some custom defined location.
Saving under specific location, for instance:
```
And save "id" field under location "topic_id"
```
Passing value of the saved location as a parameter to "fake data":
```
| parent           | (topic_id)         ||
```
Checking if the value from the location "(topic_id)" equals the value of the `parent` field from newly created object:
```
And field "parent" in the response should be "(topic_id)"
```
=> Behat - added possibility to save response specific field's value to use it later & CS-5633

newscoop/library/Newscoop/Services/Auth/DoctrineAuthService.php
this is needed to do zend_auth in the sso plugin
=> SITE-692: SSO integration support for Newscoop 4.3.x

newscoop/src/Newscoop/NewscoopBundle/Resources/views/BackendPublications/index.html.twig
The button which is only shown if there are no publications yet, didn't have a link.
=> Adds link to 'Add publication'-button

.travis.yml, newscoop/extensions/sourcefabric/SourcefabricDevFeed.php, newscoop/extensions/sourcefabric/SourcefabricFeed.php, newscoop/install/Resources/sql/upgrade/4.4.x/2015.03.11/topics.php, newscoop/library/Newscoop/Tools/Console/Command/InstallNewscoopCommand.php
=> bugfixes and improvements

newscoop/application/modules/admin/controllers/ThemesController.php, newscoop/classes/cache/TemplateCacheHandler_DB.php, newscoop/include/smarty/campsite_plugins/function.render.php, newscoop/library/Newscoop/Services/PlaylistsService.php
There was issue that template and playlists service allways exected
array for list and template properties.
I added also example for articlesLists theme.xml declaration and
examples for render function.
i removed also merging campuri vector with smarty vector - i think that it's not needed. Smarty vector in builded from CampUri one on rendering main template action, CampUri vector will not change during request processing.
=> fix handling xml content  with single items, add comments

newscoop/library/Newscoop/Services/IssueService.php
if issue listener was not called - get latest publisched issue on
fetching isue from issue service - important on rendering templates
from admin context (like 404.tpl)
=> improve issue service

newscoop/library/Newscoop/Entity/Repository/IssueRepository.php, newscoop/library/Newscoop/Services/IssueService.php, newscoop/library/Newscoop/Services/UserService.php, newscoop/src/Newscoop/ArticlesBundle/Resources/public/app/services/comments.js, newscoop/src/Newscoop/GimmeBundle/Controller/UsersController.php, newscoop/src/Newscoop/NewscoopBundle/EventListener/IssueListener.php, newscoop/src/Newscoop/NewscoopBundle/Resources/config/services.yml, newscoop/src/Newscoop/NewscoopBundle/Resources/public/js/playlists/controllers/playlists.js, newscoop/src/Newscoop/NewscoopBundle/Resources/public/js/playlists/services/auth-interceptor.js, newscoop/src/Newscoop/NewscoopBundle/Resources/public/js/playlists/services/playlists.js, newscoop/src/Newscoop/NewscoopBundle/Resources/public/js/playlists/services/user-auth.js, newscoop/src/Newscoop/NewscoopBundle/Resources/public/views/modal-login.html, newscoop/src/Newscoop/NewscoopBundle/Resources/views/PasswordRecovery/index.html.twig, newscoop/src/Newscoop/NewscoopBundle/Security/Http/Authentication/AuthenticationSuccessHandler.php, newscoop/src/Newscoop/NewscoopBundle/Security/Http/Authentication/OAuthSuccessHandler.php, newscoop/themes/system_templates/css/main.css, newscoop/themes/system_templates/oauth_login.tpl, newscoop/themes/system_templates/oauth_result.tpl, spec/Newscoop/Services/IssueServiceSpec.php
Comparison: (with IssueListener enabled on API and without it, tested on `/api/topics` endpoint)
**When user session in Newscoop is valid**
1. Access token is obtained via `/api/users/access_token` endpoint (no oauth modal).
2. When access token expires, a new token is obtained via `/api/users/access_token` endpoint (no oauth modal).
**When user session in Newscoop is invalid**
1. A modal opens with oauth form, user is redirected to `/oauth/authentication/result` after successful authentication, a new access token is obtained from the redirect uri.
PR also includes:
=> CS-5782 - ignore authentication oauth modal when session is valid

newscoop/admin-files/article_types/fields/index.php, newscoop/src/Newscoop/NewscoopBundle/Controller/WebcodeRedirectController.php
return 404 response code on not published yet  articles (when hited by
webcode)
=> hide the "show in editor" option in the article type fields for switches

newscoop/bin/newscoop-restore
If the destination folders are symlinks the restore doesn't work (backup does). This fixes the problem
=> CS-5790: Fixes issue when images/files/videos/pdf folder is symlink

newscoop/install/Resources/sql/upgrade/4.4.x/2015.03.19/init_order_in_playlists.php
When dealing with the entities in silex upgrade scripts, whose use `utcdatetime` type, this type should be registered in `DoctrineOrmServiceProvider` like:
```
'orm.em.options' => array(
'types' => array(
'utcdatetime' => 'Newscoop\NewscoopBundle\ORM\UTCDateTimeType',
),
)
```
=> added utcdatetime type to the upgrade script

newscoop/include/smarty/campsite_plugins/function.set_article.php, newscoop/library/Newscoop/Services/CacheService.php, newscoop/template_engine/classes/CampURIShortNames.php
* allow resseting article with this same number - it’s required for article change in case of switching context language
* add option to serialize objects passed to cache key
* use md4 for cache keys instead base64_encode
=> Fix key for article stored in cache

newscoop/library/Newscoop/Entity/Repository/ArticleRepository.php
Sometimes it makes more sense to fetch articles from latest to oldest.
I've search in Newscoop for this method and we only use it in place in the API and only specify 2 params there. So this shouldn't break anything.
=> TW-75: Adds parameter to sort articles descending

newscoop/src/Newscoop/NewscoopBundle/Controller/EmbedlyController.php
Used container from the zend registry because I couldn't find a quick workaround on how to inject the container into EmbedlyController.
api key for embedly needs to be provided in custom_parameters.yml file:
```
parameters:
embedly.api_key: <your_key>
```
=> added api key handling to the embedly controller

newscoop/application/AppKernel.php
Temp files for Jobby will now be put into /cache . Should prevent any issue with the lck files on a multi-newscoop hosting environment.
=> [wip] - CS-5606: Changes temp dir to project cache dir

newscoop/admin-files/articles/edit_switches_box.php, newscoop/template_engine/classes/CampContext.php
show that switch only when ‚newscoop/newscoop-paywall-bundle’ plugin is
installed
=> [CS-5814] [Fix] Article Edit sidebar still has the switch 'Visible to non-subscribers'

newscoop/include/smarty/campsite_plugins/function.generate_edit_url.php
Add smarty function generate_edit_url
Documentation is here: https://wiki.sourcefabric.org/display/NsLingo/Generate+uri+for+editing+article+from+frontend
=> [CS-5837] [New Feature] add support for other editors in smarty link function

newscoop/admin-files/articles/editor_load_tinymce.php
This adds the allowfullscreen attributes to the list of valid attributes
for an iframe-tag in the TinyMCE configuration.
=> TW-250: Adds allowfullscreen attribute as valid

newscoop/admin-files/articles/context_box/popup.php, newscoop/admin-style/admin_stylesheet_context.css
When selecting an author or creator, the select2 field would resize to
the length of the name. When removing and then re-adding the filter the
field still had the same width. Which is inconvenient if you've searched
for a short name.
=> CS-5854: Adds css fix so select2 will keep the same width

newscoop/install/Resources/sql/campsite_core.sql, newscoop/install/Resources/sql/upgrade/4.4.x/2015.06.30/tables.sql
This changes update_time on every article update (like new article
added to section and order of ther articles mush be changed). We manage
update_time manualy in the app.
=> don't update change update_time on article update

newscoop/classes/ContextBoxArticle.php, newscoop/include/smarty/campsite_plugins/block.list_related_articles.php, newscoop/template_engine/classes/BoxArticlesList.php
On frontend the parameter defaults to true (except when in preview
mode). When the parameter is set to true, it will only select related
articles that are published.
=> CS-5888: Adds parameter published to list_related_articles

newscoop/application/controllers/RegisterController.php, newscoop/application/forms/Confirm.php
Replacing {{ $form }} in the file register_confirm.tpl with the following lines will allow you to set a redirect page after a succesful confirm action.
{{ assign var="hiddenelement" value=$form->getElement('_target_path') }}
{{ $hiddenelement->setValue('<my-redirect-url>') }}
{{ $form }}
=> CS-5895: Adds check for custom redirect parameter on confirm

newscoop/classes/ContextBoxArticle.php
With the addition of the 'published' check, i added a join with the Article table. But i didn't take into account that when an article is translated, it will return the article multiple time (because we dont use the context language here). Since related articles are the same between translations anyway, a simple DISTINCT is enough to prevent duplicate article numbers from being returned.
=> CS-5903: Adds DISTINCT so related article numbers are only returned once

newscoop/admin-files/sections/duplicate.php
Use issue number from issue list, instead of issue from current publication. If the issue list is based on another publication, there is no guarantee that the issue numbers are the same.
=> CS-5898: Use issue number fetched from db

newscoop/install/Resources/sql/campsite_core.sql, newscoop/install/Resources/sql/upgrade/4.4.x/2015.08.10/tables.sql
Re-added the tables.sql to fix it for people who installed Newscoop 4.x
=> Adds auto increment to article playlist id

newscoop/admin-files/lib_campsite.php
According to the documentation a number represents the days from today
and not the actual year.
=> IM-2915: Removed date limits from search datepicker

newscoop/template_engine/classes/ArticleCommentsList.php, newscoop/template_engine/metaclasses/MetaComment.php
Template test cases
```smarty
// show only approved comments
{{ list_article_comments }}
<div class="comment" style="{{ if $gimme->comment->status === "hidden" }}color:#FFF{{ /if }}">
<p><strong>{{ $gimme->comment->nickname }}</strong><br>
{{ $gimme->comment->content }}</p>
<p><em>{{ $gimme->comment->subject }} | <span>{{ $gimme->comment->submit_date|camp_date_format:"%M %e, %Y" }}</span></em></p>
</div>
{{ /list_article_comments }}
<hr />
// show only approved comments with switch
{{ list_article_comments show_hidden=false }}
<div class="comment" style="{{ if $gimme->comment->status === "hidden" }}color:#FFF{{ /if }}">
<p><strong>{{ $gimme->comment->nickname }}</strong><br>
{{ $gimme->comment->content }}</p>
<p><em>{{ $gimme->comment->subject }} | <span>{{ …
```
=> add option to fetch hidden article comments

newscoop/install/Resources/sql/upgrade/4.4.x/2015.09.28/data-required.sql, newscoop/install/Resources/sql/upgrade/4.4.x/2015.09.28/tables.sql, newscoop/js/admin.js, newscoop/src/Newscoop/NewscoopBundle/Controller/TopicsController.php, newscoop/src/Newscoop/NewscoopBundle/Entity/Topic.php, newscoop/src/Newscoop/NewscoopBundle/Entity/TopicTranslation.php, newscoop/src/Newscoop/NewscoopBundle/Resources/public/css/new-design.css, newscoop/src/Newscoop/NewscoopBundle/Resources/public/js/angular-ui-tree-filter.min.js, newscoop/src/Newscoop/NewscoopBundle/Resources/public/js/tree.js, newscoop/src/Newscoop/NewscoopBundle/Resources/translations/topics.en.yml, newscoop/src/Newscoop/NewscoopBundle/Resources/views/Topics/index.html.twig, newscoop/src/Newscoop/NewscoopBundle/Services/TopicService.php, spec/Newscoop/GimmeBundle/Controller/TopicsControllerSpec.php
**Important changes:**
- in article edit screen when editing article's attached topics, on top of the iframe, there is a list of all attached topics for given article. Each attached topic is listed with the full path it has in the tree. When clicking on the attached topic, you will be moved to the position where this topic is located in the tree, so you can edit it, add new subtopic to it etc.
- when searching for the topic (search input), only the current "subtree" will be shown and expanded in which is found the topic of the given phrase in a search input. Other topics will be invisible in this situation, so editors can easly spot the topic in the tree and will not need to scroll down the whole tree.
- performance improvements
=> CS-5429 - Topic list is opening too long in article editor

newscoop/library/Newscoop/Entity/Repository/ArticleRepository.php, newscoop/src/Newscoop/GimmeBundle/Controller/TopicsController.php
* get in one query all needed relations (for api) - it fixes issue with missing relation object and exceptions
* order topic articles by publish date (desc) by default
=> improve fetching topic articles

newscoop/library/Newscoop/Tools/Console/Command/GenerateWebcodeCommand.php, newscoop/library/Newscoop/WebcodeFacade.php
Optimizes the generation of webcodes by removing some weird loop. 
Also adds return status to the webcode command, this way its output can 
be properly used in bash scripts.
=> [wip] - AZ-266: Adds return status to webcode command and removes weird loop

newscoop/bin/webcode_generate_all.sh, newscoop/library/Newscoop/Tools/Console/Command/GenerateWebcodeCommand.php, newscoop/library/Newscoop/WebcodeFacade.php
Sometimes the webcode generator generates a duplicate. The default webcode
command will terminate with status 1. By using the provided
webcode_generate_all.sh shell script it will keep running the webcode
generate command untill the script exits with status 0.
=> AZ-266: Add script to run webcode for many many webcodes

newscoop/library/Newscoop/Services/ThemesService.php
This would trigger PHP Notices when running newscoop-backup and
newscoop-restore.
=> CS-5942: Adds check if request is set

newscoop/classes/Publication.php, newscoop/library/Newscoop/Entity/Publication.php
The getSeo() method on the entity for Publication also type casts any
returned value from unserialize to an array, therefore getSEO() in the
legacy classes should do the same.
Plus the data type should be string, not int.
=> CS-5933: Forces getSEO() always to return an array and fixes typo

newscoop/template_engine/classes/CampHTMLDocument.php, newscoop/template_engine/classes/CampSite.php
This allows us to add as many rss or atom templates as we want. The only requirement is that they end with _rss.tpl_ or _atom.tpl_. Then the corresponding content-types will be set.
=> CS-5941: Sets different content-type for rss.tpl or atom.tpl templates

newscoop/src/Newscoop/NewscoopBundle/Controller/CommentsController.php
If an article doesnt exist in the database (deleted manually, comments were imported and articles for these comments dont exist etc), comments should be ignored in that case so it wont throw an exception and will not disable the comments management page.
=> ignore comments for not existing articles

newscoop/application/controllers/helpers/Smarty.php, newscoop/library/Newscoop/SmartyView.php, newscoop/src/Newscoop/ZendBridgeBundle/Controller/BridgeController.php
This has my preference over https://github.com/sourcefabric/Newscoop/pull/1314 because it just sets the language for the internal request and then caching is also handled etc etc.
=> CS-5931: connects symfony locale to legacy locale
